/** Mots-clés SEO par article (alignés sur blog-data.js) */
export const ARTICLE_SEO = {
  'jeux-comme-skyjo': 'alternative skyjo, jeu comme skyjo, jeux similaires skyjo',
  'meilleurs-jeux-apero': 'jeux apéro cartes, meilleurs jeux apéro, jeux soirée alcool',
  'jeux-soiree-amis': 'jeux soirée entre amis, jeux cartes adultes, jeux conviviaux',
  'jeux-famille': 'jeux famille, jeux société famille, jeux cartes enfants',
  'cadeau-anniversaire': 'cadeau jeu société anniversaire, idée cadeau jeu cartes',
  'cadeau-noel': 'cadeau noël jeu société, idée cadeau noël jeux',
  'jeux-cartes-pas-chers': 'jeux cartes pas chers, petits jeux budget, jeux société abordable',
  'alternatives-wizard': 'alternative wizard, jeu comme wizard, jeux plis wizard',
  'alternatives-uno': 'alternative uno, jeu comme uno, jeux cartes uno',
  'jeux-30-minutes': 'jeux 30 minutes, jeux rapides société, jeux courts cartes',
  'jeux-3-joueurs': 'jeux 3 joueurs, meilleurs jeux à trois, jeux société trio',
  'jeux-bluff-pari': 'jeux bluff, jeux pari cartes, jeux estimation plis',
  'jeux-debutants-adultes': 'jeux débutants adultes, jeux société faciles, initiation jeux modernes',
  'jeux-vacances-voyage': 'jeux voyage, jeux vacances compact, jeux transportables',
  'jeux-plis-comparatif': 'comparatif jeux plis, jeux de plis, wizard kyran oh hell',
  'jeux-comme-dixit': 'alternative dixit, jeu comme dixit, jeux association images',
  'jeux-comme-codenames': 'alternative codenames, jeu comme codenames, jeux équipe mots',
  'jeux-comme-hanabi': 'alternative hanabi, jeu comme hanabi, jeux coop cartes',
  'jeux-coop-cartes': 'jeux coopératifs cartes, jeux coop société, hanabi the crew',
  'jeux-duo-couples': 'jeux à deux, jeux couple, jeux 2 joueurs cartes',
  'jeux-grands-groupes': 'jeux grands groupes, jeux 8 joueurs, jeux nombreux',
  'jeux-sans-elimination': 'jeux sans élimination, jeux inclusifs société',
  'jeux-ete-terrasse': 'jeux été terrasse, jeux dehors cartes, jeux vacances',
  'jeux-strategie-legere': 'jeux stratégie légère, jeux réflexion accessibles',
  'jeux-ambiance-party': 'jeux party, jeux ambiance soirée, jeux fous rires',
  'jeux-comme-skull': 'alternative skull, jeu comme skull, jeux bluff cartes',
  'jeux-draft-encheres': 'jeux draft cartes, jeux enchères, sushi go for sale',
  'jeux-trahison-cachee': 'jeux trahison, jeux rôles cachés, saboteur bang',
  'jeux-classiques-modernes': 'jeux classiques modernes, monopoly deal uno',
  'jeux-memoire-concentration': 'jeux mémoire, jeux concentration, the mind',
  'variantes-skyjo': 'variante skyjo, variantes skyjo, autre jeu avec carte skyjo, regle alternative skyjo',
  'jeux-cartes-5-joueurs': 'jeu de carte 5 joueurs, jeux de societe 5 joueurs, jeu de cartes a 5, jeux 5 personnes',
  'jeux-comme-6-qui-prend': 'jeu comme 6 qui prend, alternative 6 qui prend, jeux similaires 6 qui prend',
  'alternatives-belote-coinche': 'jeu comme la belote, alternative belote coinche, remplacer belote, jeu de plis moderne',
  'jeux-comme-the-crew': 'jeu comme the crew, alternative the crew, jeux plis cooperatifs, jeux coop cartes',
  'jeux-cartes-4-joueurs': 'jeu de cartes 4 joueurs, meilleur jeu societe 4 joueurs, jeux de cartes a 4',
  'jeux-comme-exploding-kittens': 'jeu comme exploding kittens, alternative exploding kittens, jeux cartes pieges',
  'guide-jeux-de-plis': 'jeu de plis, regle jeu de plis, comment jouer aux plis, atout belote tarot whist',
  'jeux-brise-glace-afterwork': 'jeu brise glace soiree, jeu afterwork, jeu brise glace adulte, animation soiree collegues',
  'jeux-cartes-addictifs-poche': 'jeu de carte addictif, jeu format poche voyage, petit jeu cartes rapide'
};

export const ARTICLE_ORDER = [
  'jeux-comme-skyjo', 'meilleurs-jeux-apero', 'jeux-soiree-amis', 'jeux-famille',
  'cadeau-anniversaire', 'cadeau-noel', 'jeux-cartes-pas-chers', 'alternatives-wizard',
  'alternatives-uno', 'jeux-30-minutes', 'jeux-3-joueurs', 'jeux-bluff-pari',
  'jeux-debutants-adultes', 'jeux-vacances-voyage', 'jeux-plis-comparatif',
  'jeux-comme-dixit', 'jeux-comme-codenames', 'jeux-comme-hanabi', 'jeux-coop-cartes',
  'jeux-duo-couples', 'jeux-grands-groupes', 'jeux-sans-elimination', 'jeux-ete-terrasse',
  'jeux-strategie-legere', 'jeux-ambiance-party', 'jeux-comme-skull', 'jeux-draft-encheres',
  'jeux-trahison-cachee', 'jeux-classiques-modernes', 'jeux-memoire-concentration',
  'variantes-skyjo', 'jeux-cartes-5-joueurs', 'jeux-comme-6-qui-prend', 'alternatives-belote-coinche',
  'jeux-comme-the-crew', 'jeux-cartes-4-joueurs', 'jeux-comme-exploding-kittens', 'guide-jeux-de-plis',
  'jeux-brise-glace-afterwork', 'jeux-cartes-addictifs-poche'
];
